apiVersion: v1
kind: Secret
metadata:
  name: github-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJaV2gxWjI5dWJtVXJjWFZoZVY5eWIySnZkRHBEVlZaWVRVMUZUalE1UjFGYU1rWXlXVFJXVFVkTVZFaElVMHhhUTFKTk9USlhWRFF3T1RKWk1rVTVNbE5QU2pNNE1qaFBNekpST1RSU00xQlVRVnBCIiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson