apiVersion: v2
name: wildfly
description: Build and Deploy WildFly applications on OpenShift
type: "application"
version: 2.4.0

kubeVersion: ">= 1.19.0-0"
home: https://wildfly.org

maintainers:
  - email: wildfly-dev@lists.jboss.org
    name: WildFly
    url: https://wildfly.org
icon: https://design.jboss.org/wildfly/logo/final/wildfly_logomark_256px.png

annotations:
  charts.openshift.io/name: WildFly
  charts.openshift.io/provider: WildFly
  artifacthub.io/category: ApplicationServer
  artifacthub.io/images: |
    - name: builderImage
      image: quay.io/wildfly/wildfly-s2i:latest
    - name: runtimeImage
      image: quay.io/wildfly/wildfly-runtime:latest
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: E15B52A4F0910E4323D19C6772C04F9E7CBD2B0D
    url: https://keyserver.ubuntu.com   

dependencies:
- name: wildfly-common
  version: 2.2.0
  repository: file://../wildfly-common
