name: Helm Chart CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Setup Bats and Bats libs
        uses: bats-core/bats-action@1.5.4
        with:
          bats-version: 1.10.0
          support-path: ${{ github.workspace }}/tests/test-common/bats-support
          assert-path: ${{ github.workspace }}/tests/test-common/bats-assert

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          node_image: "kindest/node:v1.29.0"
          config: ./.github/workflows/ci/kind-config.yaml
          cluster_name: chart-testing

      - name: Setup Image registry
        run: |-
          ./.github/workflows/ci/setup-image-registry.sh
      - name: Setup Nginx Ingress Controller
        run: |-
          ./.github/workflows/ci/setup-nginx-ingress-controller.sh
      - name: Modify /etc/hosts
        run: |-
           sudo echo "127.0.0.1 wildfly.local" | sudo tee -a /etc/hosts
      - name: Run Tests
        run: |-
          cd tests/bats
          bats -r .
